export const data = [
	{
		id: 1,
		image: "img/trending/trending01.webp",
		title: "Adidas Ultra Boost",
		text: "Yes",
		price: "180",
		stars: 4.8,
		isTrending: true,
		colors: ["Black", "White"],
		description: "High-performance running shoes designed for comfort and durability.",
		category: "Running",
		brand: "Adidas",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-789012"
	},
	{
		id: 2,
		image: "img/trending/trending02.webp",
		title: "Nike Air Max 270",
		text: "No",
		price: "150",
		stars: 4.5,
		isTrending: true,
		colors: ["Red", "Black"],
		description: "Stylish sneakers with excellent cushioning for everyday wear.",
		category: "Lifestyle",
		brand: "Nike",
		availableSizes: [38, 39, 40, 41, 42],
		codeProduct: "SKU-345678"
	},
	{
		id: 3,
		image: "img/trending/trending03.webp",
		title: "Puma Ignite",
		text: "Yes",
		price: "130",
		stars: 4.2,
		isTrending: false,
		colors: ["Blue", "Gray"],
		description: "Lightweight and breathable, perfect for active lifestyles.",
		category: "Training",
		brand: "Puma",
		availableSizes: [39, 40, 41, 42, 43],
		codeProduct: "SKU-901234"
	},
	{
		id: 4,
		image: "img/trending/trending04.webp",
		title: "Reebok Zig Kinetica",
		text: "No",
		price: "120",
		stars: 4.0,
		isTrending: true,
		colors: ["White", "Orange"],
		description: "Innovative design with energy-returning soles for optimal performance.",
		category: "Running",
		brand: "Reebok",
		availableSizes: [40, 41, 42, 43, 44],
		codeProduct: "SKU-567890"
	},
	{
		id: 5,
		image: "img/trending/trending05.webp",
		title: "Converse All Star",
		text: "Yes",
		price: "110",
		stars: 4.7,
		isTrending: true,
		colors: ["Black", "Red"],
		description: "A timeless classic that never goes out of style.",
		category: "Casual",
		brand: "Converse",
		availableSizes: [36, 37, 38, 39, 40],
		codeProduct: "SKU-234567"
	},
	{
		id: 6,
		image: "img/trending/trending06.webp",
		title: "Vans Classic",
		text: "No",
		price: "90",
		stars: 4.3,
		isTrending: false,
		colors: ["Gray", "White"],
		description: "Perfect for skateboarding and casual outings.",
		category: "Skateboarding",
		brand: "Vans",
		availableSizes: [37, 38, 39, 40, 41],
		codeProduct: "SKU-890123"
	},
	{
		id: 7,
		image: "img/trending/trending07.webp",
		title: "New Balance 990",
		text: "Yes",
		price: "170",
		stars: 4.6,
		isTrending: true,
		colors: ["Navy", "Gray"],
		description: "Premium quality sneakers with exceptional arch support.",
		category: "Walking",
		brand: "New Balance",
		availableSizes: [41, 42, 43, 44, 45],
		codeProduct: "SKU-456789"
	},
	{
		id: 8,
		image: "img/trending/trending08.webp",
		title: "Under Armour HOVR Phantom",
		text: "Yes",
		price: "160",
		stars: 4.4,
		isTrending: true,
		colors: ["Black", "Blue"],
		description: "Advanced cushioning for high-impact activities.",
		category: "Training",
		brand: "Under Armour",
		availableSizes: [39, 40, 41, 42, 43],
		codeProduct: "SKU-678901"
	},
	{
		id: 9,
		image: "img/trending/trending9.webp",
		title: "Jordan Retro 4",
		text: "No",
		price: "200",
		stars: 4.9,
		isTrending: true,
		colors: ["Red", "White"],
		description: "Iconic basketball sneakers with a bold design.",
		category: "Basketball",
		brand: "Jordan",
		availableSizes: [42, 43, 44, 45, 46],
		codeProduct: "SKU-345012"
	},
	{
		id: 10,
		image: "img/trending/trending10.webp",
		title: "Asics Gel Kayano",
		text: "Yes",
		price: "140",
		stars: 4.3,
		isTrending: false,
		colors: ["White", "Green"],
		description: "Designed for long-distance runners with excellent support.",
		category: "Running",
		brand: "Asics",
		availableSizes: [40, 41, 42, 43, 44],
		codeProduct: "SKU-901567"
	},
	{
		id: 11,
		image: "img/trending/trending11.webp",
		title: "Saucony Endorphin",
		text: "Yes",
		price: "130",
		stars: 4.1,
		isTrending: false,
		colors: ["Black", "Yellow"],
		description: "Engineered for speed and responsiveness on the track.",
		category: "Track",
		brand: "Saucony",
		availableSizes: [38, 39, 40, 41, 42],
		codeProduct: "SKU-234890"
	},
	{
		id: 12,
		image: "img/trending/trending12.webp",
		title: "Hoka One One Clifton",
		text: "No",
		price: "150",
		stars: 4.6,
		isTrending: true,
		colors: ["Blue", "Orange"],
		description: "Maximalist cushioning for unparalleled comfort during runs.",
		category: "Running",
		brand: "Hoka One One",
		availableSizes: [41, 42, 43, 44, 45],
		codeProduct: "SKU-567123"
	},
	{
		id: 13,
		image: "img/trending/trending13.webp",
		title: "Adidas NMD",
		text: "Yes",
		price: "180",
		stars: 4.8,
		isTrending: true,
		colors: ["White", "Black"],
		description: "A sleek design blending modern aesthetics and comfort.",
		category: "Lifestyle",
		brand: "Adidas",
		availableSizes: [39, 40, 41, 42, 43],
		codeProduct: "SKU-890456"
	},
	{
		id: 14,
		image: "img/trending/trending14.webp",
		title: "Nike React Infinity",
		text: "No",
		price: "160",
		stars: 4.5,
		isTrending: true,
		colors: ["Green", "Black"],
		description: "Built for stability and long-lasting performance.",
		category: "Running",
		brand: "Nike",
		availableSizes: [40, 41, 42, 43, 44],
		codeProduct: "SKU-123890"
	},
	{
		id: 15,
		image: "img/trending/trending15.webp",
		title: "Puma Future Rider",
		text: "Yes",
		price: "100",
		stars: 4.0,
		isTrending: false,
		colors: ["Pink", "Gray"],
		description: "Retro-inspired sneakers with a playful touch.",
		category: "Casual",
		brand: "Puma",
		availableSizes: [38, 39, 40, 41, 42],
		codeProduct: "SKU-456012"
	},
	{
		id: 16,
		image: "img/trending/trending16.webp",
		title: "Brooks Ghost 14",
		text: "Yes",
		price: "130",
		stars: 4.7,
		isTrending: true,
		colors: ["Blue", "Silver"],
		description: "Smooth ride with balanced cushioning for daily runs.",
		category: "Running",
		brand: "Brooks",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "US Men",
		codeProduct: "SKU-789345"
	},
	{
		id: 17,
		image: "img/trending/trending17.webp",
		title: "Skechers Go Walk 6",
		text: "No",
		price: "75",
		stars: 4.2,
		isTrending: false,
		colors: ["Black", "Gray"],
		description: "Lightweight and comfortable walking shoes with breathable mesh.",
		category: "Walking",
		brand: "Skechers",
		availableSizes: [37, 38, 39, 40, 41],
		sizeDetail: "US Women",
		codeProduct: "SKU-012678"
	},
	{
		id: 18,
		image: "img/trending/trending18.webp",
		title: "On Cloudswift",
		text: "Yes",
		price: "140",
		stars: 4.6,
		isTrending: true,
		colors: ["White", "Blue"],
		description: "Engineered for urban running with superior cushioning.",
		category: "Running",
		brand: "On",
		availableSizes: [39, 40, 41, 42, 43],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-345901"
	},
	{
		id: 19,
		image: "img/trending/trending19.webp",
		title: "Salomon Speedcross 5",
		text: "Yes",
		price: "120",
		stars: 4.4,
		isTrending: false,
		colors: ["Black", "Red"],
		description: "Trail running shoes with aggressive grip for rugged terrains.",
		category: "Trail Running",
		brand: "Salomon",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-678234"
	},
	{
		id: 20,
		image: "img/trending/trending20.webp",
		title: "Mizuno Wave Rider 25",
		text: "No",
		price: "135",
		stars: 4.5,
		isTrending: true,
		colors: ["White", "Blue"],
		description: "Reliable and responsive running shoes for all distances.",
		category: "Running",
		brand: "Mizuno",
		availableSizes: [41, 42, 43, 44, 45],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-901567"
	},
	{
		id: 21,
		image: "img/trending/trending21.webp",
		title: "Fila Disruptor 2",
		text: "Yes",
		price: "85",
		stars: 4.1,
		isTrending: false,
		colors: ["White", "Pink"],
		description: "Chunky sneakers with a bold, retro-inspired design.",
		category: "Casual",
		brand: "Fila",
		availableSizes: [36, 37, 38, 39, 40],
		sizeDetail: "US Women",
		codeProduct: "SKU-234678"
	},
	{
		id: 22,
		image: "img/trending/trending22.webp",
		title: "Diadora Game L Low",
		text: "No",
		price: "95",
		stars: 4.3,
		isTrending: true,
		colors: ["White", "Green"],
		description: "Classic tennis shoes with a modern twist.",
		category: "Tennis",
		brand: "Diadora",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-567901"
	},
	{
		id: 23,
		image: "img/trending/trending23.webp",
		title: "Lacoste Carnaby Evo",
		text: "Yes",
		price: "110",
		stars: 4.0,
		isTrending: false,
		colors: ["White", "Blue"],
		description: "Stylish and comfortable sneakers for everyday wear.",
		category: "Casual",
		brand: "Lacoste",
		availableSizes: [38, 39, 40, 41, 42],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-890234"
	},
	{
		id: 24,
		image: "img/trending/trending24.webp",
		title: "Ecco Soft 7",
		text: "Yes",
		price: "150",
		stars: 4.6,
		isTrending: true,
		colors: ["Black", "Brown"],
		description: "Premium leather sneakers with exceptional comfort.",
		category: "Casual",
		brand: "Ecco",
		availableSizes: [39, 40, 41, 42, 43],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-123567"
	},
	{
		id: 25,
		image: "img/trending/trending25.webp",
		title: "Timberland Euro Hiker",
		text: "No",
		price: "170",
		stars: 4.4,
		isTrending: false,
		isNew: false,
		discountRate: 18,
		gender: "men",
		colors: ["Brown", "Black"],
		description: "Durable hiking boots designed for rugged adventures.",
		category: "Hiking",
		brand: "Timberland",
		availableSizes: [41, 42, 43, 44, 45],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-456890"
	},
	{
		id: 26,
		image: "img/trending/trending04.webp",
		title: "Nike Zoom Fly Street",
		text: "Yes",
		price: "165",
		stars: 4.7,
		isTrending: true,
		isNew: true,
		discountRate: 0,
		gender: "men",
		colors: ["Navy", "White"],
		description: "Responsive foam and a race-inspired profile made for urban runners.",
		category: "Running",
		brand: "Nike",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "EU Men",
		codeProduct: "SKU-112600"
	},
	{
		id: 27,
		image: "img/trending/trending05.webp",
		title: "Adidas Samba Luxe",
		text: "Yes",
		price: "135",
		stars: 4.6,
		isTrending: true,
		isNew: true,
		discountRate: 10,
		gender: "women",
		colors: ["White", "Beige"],
		description: "Premium leather update of an icon with modern cushioning.",
		category: "Lifestyle",
		brand: "Adidas",
		availableSizes: [36, 37, 38, 39, 40],
		sizeDetail: "EU Women",
		codeProduct: "SKU-112701"
	},
	{
		id: 28,
		image: "img/trending/trending06.webp",
		title: "Puma Velocity Nitro",
		text: "No",
		price: "145",
		stars: 4.4,
		isTrending: false,
		isNew: true,
		discountRate: 8,
		gender: "men",
		colors: ["Black", "LimeGreen"],
		description: "Lightweight trainer engineered for tempo workouts and long runs.",
		category: "Running",
		brand: "Puma",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "EU Men",
		codeProduct: "SKU-112802"
	},
	{
		id: 29,
		image: "img/trending/trending07.webp",
		title: "Reebok Club C Lift",
		text: "Yes",
		price: "115",
		stars: 4.3,
		isTrending: false,
		isNew: true,
		discountRate: 22,
		gender: "women",
		colors: ["White", "LightGray"],
		description: "Retro tennis DNA elevated by platform comfort and clean lines.",
		category: "Casual",
		brand: "Reebok",
		availableSizes: [36, 37, 38, 39, 40],
		sizeDetail: "EU Women",
		codeProduct: "SKU-112903"
	},
	{
		id: 30,
		image: "img/trending/trending08.webp",
		title: "Asics Novablast Edge",
		text: "Yes",
		price: "155",
		stars: 4.8,
		isTrending: true,
		isNew: true,
		discountRate: 0,
		gender: "women",
		colors: ["Coral", "White"],
		description: "Energetic rebound and breathable mesh tuned for daily comfort.",
		category: "Running",
		brand: "Asics",
		availableSizes: [36, 37, 38, 39, 40],
		sizeDetail: "EU Women",
		codeProduct: "SKU-113004"
	},
	{
		id: 31,
		image: "img/trending/trending10.webp",
		title: "New Balance 327 Canvas",
		text: "No",
		price: "125",
		stars: 4.2,
		isTrending: false,
		isNew: false,
		discountRate: 15,
		gender: "men",
		colors: ["Olive", "Black"],
		description: "Vintage-inspired upper with modern sole geometry for city wear.",
		category: "Lifestyle",
		brand: "New Balance",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "EU Men",
		codeProduct: "SKU-113105"
	},
	{
		id: 32,
		image: "img/trending/trending11.webp",
		title: "On Cloudnova Shift",
		text: "Yes",
		price: "175",
		stars: 4.9,
		isTrending: true,
		isNew: true,
		discountRate: 6,
		gender: "women",
		colors: ["White", "SkyBlue"],
		description: "Sleek silhouette with adaptive cushioning for all-day movement.",
		category: "Walking",
		brand: "On",
		availableSizes: [36, 37, 38, 39, 40],
		sizeDetail: "EU Women",
		codeProduct: "SKU-113206"
	},
	{
		id: 33,
		image: "img/trending/trending12.webp",
		title: "Converse Run Star Motion",
		text: "Yes",
		price: "120",
		stars: 4.5,
		isTrending: true,
		isNew: false,
		discountRate: 28,
		gender: "women",
		colors: ["Black", "White"],
		description: "Bold, sculpted sole with classic canvas attitude.",
		category: "Casual",
		brand: "Converse",
		availableSizes: [36, 37, 38, 39, 40],
		sizeDetail: "EU Women",
		codeProduct: "SKU-113307"
	},
	{
		id: 34,
		image: "img/trending/trending13.webp",
		title: "Jordan Delta Court",
		text: "No",
		price: "185",
		stars: 4.6,
		isTrending: true,
		isNew: false,
		discountRate: 14,
		gender: "men",
		colors: ["Red", "Black"],
		description: "Court-inspired lifestyle pair with premium layered materials.",
		category: "Basketball",
		brand: "Jordan",
		availableSizes: [41, 42, 43, 44, 45],
		sizeDetail: "EU Men",
		codeProduct: "SKU-113408"
	},
	{
		id: 35,
		image: "img/trending/trending14.webp",
		title: "Vans UltraRange Neo",
		text: "Yes",
		price: "108",
		stars: 4.1,
		isTrending: false,
		isNew: true,
		discountRate: 12,
		gender: "men",
		colors: ["Gray", "Orange"],
		description: "Flexible all-terrain sneaker built for commute and weekend trails.",
		category: "Skateboarding",
		brand: "Vans",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "EU Men",
		codeProduct: "SKU-113509"
	},
	{
		id: 36,
		image: "img/trending/trending15.webp",
		title: "Saucony Kinvara Flow",
		text: "Yes",
		price: "138",
		stars: 4.7,
		isTrending: true,
		isNew: true,
		discountRate: 5,
		gender: "women",
		colors: ["Purple", "White"],
		description: "Fast, natural-feel cushioning designed for speed sessions.",
		category: "Track",
		brand: "Saucony",
		availableSizes: [36, 37, 38, 39, 40],
		sizeDetail: "EU Women",
		codeProduct: "SKU-113610"
	}
];