export const reviews = [
	{
		id: 1,
		name: "Jordan D.",
		gender: "male",
		message: "Consequat cupidatat officia in pariatur nulla Lorem dolor nulla duis voluptate.",
		date: new Date("2024-12-21").getTime(),
		email: "jordan.doe@example.com",
		phone: "+123456789",
		status: "Active",
		priority: "High",
		linkedto: "HQ4540",
		rating: [
			{ ref: "CT8012-104", mark: "3" },
			{ ref: "HQ1002", mark: "4" },
		],
	},
	{
		id: 2,
		name: "Emily R.",
		gender: "unknown",
		message: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.",
		date: new Date("2024-12-22").getTime(),
		email: "emily.rose@example.com",
		phone: "+987654321",
		status: "Pending",
		priority: "Medium",
		rating: [
			{ ref: "DN3707-010", mark: "4" },
			{ ref: "EM2002", mark: "3" },
		],
	},
	{
		id: 3,
		name: "Michael B.",
		gender: "male",
		message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
		date: new Date("2024-12-23").getTime(),
		email: "michael.b@example.com",
		phone: "+456789123",
		status: "Resolved",
		priority: "Low",
		rating: [
			{ ref: "MB3001", mark: "3" },
			{ ref: "MB3002", mark: "2" },
		],
	},
	{
		id: 4,
		name: "Sophia L.",
		gender: "female",
		message: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
		date: new Date("2024-12-24").getTime(),
		email: "sophia.l@example.com",
		phone: "+321654987",
		status: "Active",
		priority: "High",
		rating: [
			{ ref: "DN3707-010", mark: "5" },
			{ ref: "SL4002", mark: "4" },
		],
	},
	{
		id: 5,
		name: "James W.",
		gender: "male",
		message: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.",
		date: new Date("2025-01-06").getTime(),
		email: "james.w@example.com",
		phone: "+789123456",
		status: "Pending",
		priority: "Medium",
		rating: [
			{ ref: "JW5001", mark: "4" },
			{ ref: "JW5002", mark: "3" },
		],
	},
	{
		id: 6,
		name: "Olivia P.",
		gender: "female",
		message: "Cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat.",
		date: new Date("2025-01-03").getTime(),
		email: "olivia.p@example.com",
		phone: "+654789321",
		status: "Resolved",
		priority: "Low",
		rating: [
			{ ref: "OP6001", mark: "3" },
			{ ref: "OP6002", mark: "2" },
		],
	},
	{
		id: 7,
		name: "Liam T.",
		gender: "male",
		message: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.",
		date: new Date("2024-11-27").getTime(),
		email: "liam.t@example.com",
		phone: "+147258369",
		status: "Active",
		priority: "High",
		rating: [
			{ ref: "LT7001", mark: "5" },
			{ ref: "LT7002", mark: "4" },
		],
	},
	{
		id: 8,
		name: "Emma K.",
		gender: "female",
		message: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis.",
		date: new Date("2024-12-30").getTime(),
		email: "emma.k@example.com",
		phone: "+369258147",
		status: "Pending",
		priority: "Medium",
		rating: [
			{ ref: "EK8001", mark: "4" },
			{ ref: "EK8002", mark: "3" },
		],
	},
	{
		id: 9,
		name: "Charlotte M.",
		gender: "female",
		message: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil.",
		date: new Date("2025-01-02").getTime(),
		email: "charlotte.m@example.com",
		phone: "+123123123",
		status: "Resolved",
		priority: "Low",
		rating: [
			{ ref: "CM9001", mark: "3" },
			{ ref: "CM9002", mark: "2" },
		],
	},
	{
		id: 10,
		name: "Ethan H.",
		gender: "male",
		message: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
		date: new Date("2024-12-29").getTime(),
		email: "ethan.h@example.com",
		phone: "+321321321",
		status: "Active",
		priority: "High",
		rating: [
			{ ref: "EH10001", mark: "5" },
			{ ref: "EH10002", mark: "4" },
		],
	},
	{
		id: 11,
		name: "Isabella F.",
		gender: "female",
		message: "Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus.",
		date: new Date("2025-01-04").getTime(),
		email: "isabella.f@example.com",
		phone: "+987987987",
		status: "Pending",
		priority: "Medium",
		rating: [
			{ ref: "IF11001", mark: "4" },
			{ ref: "IF11002", mark: "3" },
		],
	},
	{
		id: 12,
		name: "William C.",
		gender: "male",
		message: "Et harum quidem rerum facilis est et expedita distinctio.",
		date: new Date("2025-01-01").getTime(),
		email: "william.c@example.com",
		phone: "+654654654",
		status: "Resolved",
		priority: "Low",
		rating: [
			{ ref: "DN3707-010", mark: "4" },
			{ ref: "CT8012-104", mark: "5" },
		],
	},
];
