export const data = [
	{
		id: 1,
		image: "img/img_trending/trending01.png",
		title: "Adidas Ultra Boost",
		text: "Yes",
		price: "180",
		stars: 4.8,
		isTrending: true,
		colors: ["Black", "White"],
		description: "High-performance running shoes designed for comfort and durability.",
		category: "Running",
		brand: "Adidas",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-123456"
	},
	{
		id: 2,
		image: "img/img_trending/trending02.png",
		title: "Nike Air Max 270",
		text: "No",
		price: "150",
		stars: 4.5,
		isTrending: true,
		colors: ["Red", "Black"],
		description: "Stylish sneakers with excellent cushioning for everyday wear.",
		category: "Lifestyle",
		brand: "Nike",
		availableSizes: [38, 39, 40, 41, 42]
	},
	{
		id: 3,
		image: "img/img_trending/trending03.png",
		title: "Puma Ignite",
		text: "Yes",
		price: "130",
		stars: 4.2,
		isTrending: false,
		colors: ["Blue", "Gray"],
		description: "Lightweight and breathable, perfect for active lifestyles.",
		category: "Training",
		brand: "Puma",
		availableSizes: [39, 40, 41, 42, 43]
	},
	{
		id: 4,
		image: "img/img_trending/trending04.png",
		title: "Reebok Zig Kinetica",
		text: "No",
		price: "120",
		stars: 4.0,
		isTrending: true,
		colors: ["White", "Orange"],
		description: "Innovative design with energy-returning soles for optimal performance.",
		category: "Running",
		brand: "Reebok",
		availableSizes: [40, 41, 42, 43, 44]
	},
	{
		id: 5,
		image: "img/img_trending/trending05.png",
		title: "Converse All Star",
		text: "Yes",
		price: "110",
		stars: 4.7,
		isTrending: true,
		colors: ["Black", "Red"],
		description: "A timeless classic that never goes out of style.",
		category: "Casual",
		brand: "Converse",
		availableSizes: [36, 37, 38, 39, 40]
	},
	{
		id: 6,
		image: "img/img_trending/trending06.png",
		title: "Vans Classic",
		text: "No",
		price: "90",
		stars: 4.3,
		isTrending: false,
		colors: ["Gray", "White"],
		description: "Perfect for skateboarding and casual outings.",
		category: "Skateboarding",
		brand: "Vans",
		availableSizes: [37, 38, 39, 40, 41]
	},
	{
		id: 7,
		image: "img/img_trending/trending07.png",
		title: "New Balance 990",
		text: "Yes",
		price: "170",
		stars: 4.6,
		isTrending: true,
		colors: ["Navy", "Gray"],
		description: "Premium quality sneakers with exceptional arch support.",
		category: "Walking",
		brand: "New Balance",
		availableSizes: [41, 42, 43, 44, 45]
	},
	{
		id: 8,
		image: "img/img_trending/trending08.png",
		title: "Under Armour HOVR Phantom",
		text: "Yes",
		price: "160",
		stars: 4.4,
		isTrending: true,
		colors: ["Black", "Blue"],
		description: "Advanced cushioning for high-impact activities.",
		category: "Training",
		brand: "Under Armour",
		availableSizes: [39, 40, 41, 42, 43]
	},
	{
		id: 9,
		image: "img/img_trending/trending9.png",
		title: "Jordan Retro 4",
		text: "No",
		price: "200",
		stars: 4.9,
		isTrending: true,
		colors: ["Red", "White"],
		description: "Iconic basketball sneakers with a bold design.",
		category: "Basketball",
		brand: "Jordan",
		availableSizes: [42, 43, 44, 45, 46]
	},
	{
		id: 10,
		image: "img/img_trending/trending10.png",
		title: "Asics Gel Kayano",
		text: "Yes",
		price: "140",
		stars: 4.3,
		isTrending: false,
		colors: ["White", "Green"],
		description: "Designed for long-distance runners with excellent support.",
		category: "Running",
		brand: "Asics",
		availableSizes: [40, 41, 42, 43, 44]
	},
	{
		id: 11,
		image: "img/img_trending/trending11.png",
		title: "Saucony Endorphin",
		text: "Yes",
		price: "130",
		stars: 4.1,
		isTrending: false,
		colors: ["Black", "Yellow"],
		description: "Engineered for speed and responsiveness on the track.",
		category: "Track",
		brand: "Saucony",
		availableSizes: [38, 39, 40, 41, 42]
	},
	{
		id: 12,
		image: "img/img_trending/trending12.png",
		title: "Hoka One One Clifton",
		text: "No",
		price: "150",
		stars: 4.6,
		isTrending: true,
		colors: ["Blue", "Orange"],
		description: "Maximalist cushioning for unparalleled comfort during runs.",
		category: "Running",
		brand: "Hoka One One",
		availableSizes: [41, 42, 43, 44, 45]
	},
	{
		id: 13,
		image: "img/img_trending/trending13.png",
		title: "Adidas NMD",
		text: "Yes",
		price: "180",
		stars: 4.8,
		isTrending: true,
		colors: ["White", "Black"],
		description: "A sleek design blending modern aesthetics and comfort.",
		category: "Lifestyle",
		brand: "Adidas",
		availableSizes: [39, 40, 41, 42, 43]
	},
	{
		id: 14,
		image: "img/img_trending/trending14.png",
		title: "Nike React Infinity",
		text: "No",
		price: "160",
		stars: 4.5,
		isTrending: true,
		colors: ["Green", "Black"],
		description: "Built for stability and long-lasting performance.",
		category: "Running",
		brand: "Nike",
		availableSizes: [40, 41, 42, 43, 44]
	},
	{
		id: 15,
		image: "img/img_trending/trending15.png",
		title: "Puma Future Rider",
		text: "Yes",
		price: "100",
		stars: 4.0,
		isTrending: false,
		colors: ["Pink", "Gray"],
		description: "Retro-inspired sneakers with a playful touch.",
		category: "Casual",
		brand: "Puma",
		availableSizes: [38, 39, 40, 41, 42]
	},
	{
		id: 16,
		image: "img/img_trending/trending16.png",
		title: "Brooks Ghost 14",
		text: "Yes",
		price: "130",
		stars: 4.7,
		isTrending: true,
		colors: ["Blue", "Silver"],
		description: "Smooth ride with balanced cushioning for daily runs.",
		category: "Running",
		brand: "Brooks",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "US Men",
		codeProduct: "SKU-654321"
	},
	{
		id: 17,
		image: "img/img_trending/trending17.png",
		title: "Skechers Go Walk 6",
		text: "No",
		price: "75",
		stars: 4.2,
		isTrending: false,
		colors: ["Black", "Gray"],
		description: "Lightweight and comfortable walking shoes with breathable mesh.",
		category: "Walking",
		brand: "Skechers",
		availableSizes: [37, 38, 39, 40, 41],
		sizeDetail: "US Women",
		codeProduct: "SKU-987654"
	},
	{
		id: 18,
		image: "img/img_trending/trending18.png",
		title: "On Cloudswift",
		text: "Yes",
		price: "140",
		stars: 4.6,
		isTrending: true,
		colors: ["White", "Blue"],
		description: "Engineered for urban running with superior cushioning.",
		category: "Running",
		brand: "On",
		availableSizes: [39, 40, 41, 42, 43],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-112233"
	},
	{
		id: 19,
		image: "img/img_trending/trending19.png",
		title: "Salomon Speedcross 5",
		text: "Yes",
		price: "120",
		stars: 4.4,
		isTrending: false,
		colors: ["Black", "Red"],
		description: "Trail running shoes with aggressive grip for rugged terrains.",
		category: "Trail Running",
		brand: "Salomon",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-445566"
	},
	{
		id: 20,
		image: "img/img_trending/trending20.png",
		title: "Mizuno Wave Rider 25",
		text: "No",
		price: "135",
		stars: 4.5,
		isTrending: true,
		colors: ["White", "Blue"],
		description: "Reliable and responsive running shoes for all distances.",
		category: "Running",
		brand: "Mizuno",
		availableSizes: [41, 42, 43, 44, 45],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-778899"
	},
	{
		id: 21,
		image: "img/img_trending/trending21.png",
		title: "Fila Disruptor 2",
		text: "Yes",
		price: "85",
		stars: 4.1,
		isTrending: false,
		colors: ["White", "Pink"],
		description: "Chunky sneakers with a bold, retro-inspired design.",
		category: "Casual",
		brand: "Fila",
		availableSizes: [36, 37, 38, 39, 40],
		sizeDetail: "US Women",
		codeProduct: "SKU-990011"
	},
	{
		id: 22,
		image: "img/img_trending/trending22.png",
		title: "Diadora Game L Low",
		text: "No",
		price: "95",
		stars: 4.3,
		isTrending: true,
		colors: ["White", "Green"],
		description: "Classic tennis shoes with a modern twist.",
		category: "Tennis",
		brand: "Diadora",
		availableSizes: [40, 41, 42, 43, 44],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-223344"
	},
	{
		id: 23,
		image: "img/img_trending/trending23.png",
		title: "Lacoste Carnaby Evo",
		text: "Yes",
		price: "110",
		stars: 4.0,
		isTrending: false,
		colors: ["White", "Blue"],
		description: "Stylish and comfortable sneakers for everyday wear.",
		category: "Casual",
		brand: "Lacoste",
		availableSizes: [38, 39, 40, 41, 42],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-556677"
	},
	{
		id: 24,
		image: "img/img_trending/trending24.png",
		title: "Ecco Soft 7",
		text: "Yes",
		price: "150",
		stars: 4.6,
		isTrending: true,
		colors: ["Black", "Brown"],
		description: "Premium leather sneakers with exceptional comfort.",
		category: "Casual",
		brand: "Ecco",
		availableSizes: [39, 40, 41, 42, 43],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-334455"
	},
	{
		id: 25,
		image: "img/img_trending/trending25.png",
		title: "Timberland Euro Hiker",
		text: "No",
		price: "170",
		stars: 4.4,
		isTrending: false,
		colors: ["Brown", "Black"],
		description: "Durable hiking boots designed for rugged adventures.",
		category: "Hiking",
		brand: "Timberland",
		availableSizes: [41, 42, 43, 44, 45],
		sizeDetail: "Eu Men",
		codeProduct: "SKU-667788"
	}
];
